server:
  port: ${service.port:8090}
  contextPath: ${contextPath:/}

eureka:
  instance:
    nonSecurePort: 8090
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${APP_VERSION}:${spring.application.instance_id:${HOSTNAME}}
    metadataMap:
      instanceId: ${spring.application.name}_v${APP_VERSION}:${spring.application.instance_id:${HOSTNAME}}
      version: ${APP_VERSION}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:hsqldb:file:/.build/testdb
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: true
    database: HSQL
